config/routes.rb
Rails.application.routes.draw do
  resources :tickets
  get 'dashboard' => 'dashboard#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ticket.rb
class Ticket < ApplicationRecord
enum priority: [:high, :low]


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

    def index
        
    @high = Ticket.high
    @low = Ticket.low
    end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:Tasks, :Description, :Priority, :Starttime, :Finishtime)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/dashboard/index.html.erb
<p id="notice"><%= notice %></p>

<h1>High Priority Tickets</h1>

<table>
  <thead>
    <tr>
      <th>Tasks</th>
      <th>Description</th>
      <th>Priority</th>
    </tr>
  </thead>

  <tbody>
    <% @high.each do |h| %>
      <tr>
        <td><%= h.Tasks %></td>
        <td><%= h.Description %></td>
        <td><%= h.Priority %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>



<%= link_to 'New Ticket', new_ticket_path %>
<%= link_to 'Ticket list', tickets_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tickets/_form.html.erb
<%= form_for(ticket) do |f| %>
  <% if ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Tasks %>
    <%= f.text_field :Tasks %>
  </div>

  <div class="field">
    <%= f.label :Description %>
    <%= f.text_field :Description %>
  </div>

  <div class="field">
    <%= f.label :Priority %>
    <%= f.text_field :Priority %>
  </div>

  <div class="field">
    <%= f.label :Starttime %>
    <%= f.text_field :Starttime %>
  </div>

  <div class="field">
    <%= f.label :Finishtime %>
    <%= f.text_field :Finishtime %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tickets</h1>

<table>
  <thead>
    <tr>
      <th>Tasks</th>
      <th>Description</th>
      <th>Priority</th>
      <th>Starttime</th>
      <th>Finishtime</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.Tasks %></td>
        <td><%= ticket.Description %></td>
        <td><%= ticket.Priority %></td>
        <td><%= ticket.Starttime %></td>
        <td><%= ticket.Finishtime %></td>
        <td><%= link_to 'Show', ticket %></td>
        <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
        <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticket', new_ticket_path %>
<%= link_to 'Dashboard', dashboard_path %>

app/views/tickets/new.html.erb
<h1>New Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tasks:</strong>
  <%= @ticket.Tasks %>
</p>

<p>
  <strong>Description:</strong>
  <%= @ticket.Description %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @ticket.Priority %>
</p>

<p>
  <strong>Starttime:</strong>
  <%= @ticket.Starttime %>
</p>

<p>
  <strong>Finishtime:</strong>
  <%= @ticket.Finishtime %>
</p>

<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>